### ISSUE TITLE
Incorrect child tasks indicator count

### ISSUE THREAD

**Issue by luisbocanegra** [alexankitty/FancyTasks#1]
Having two or more windows of the same application the indicator shows a extra dot
![image](https://user-images.githubusercontent.com/15076387/198287709-addf5a17-64ba-4011-a016-82bdec9ec947.png)

**Comment by alexankitty** [comment]
Thanks for pointing this out. I will look into where this issue might be, and reply back with anything I find. I'm working at the moment, so it might be a bit before I can get to this.

**Comment by alexankitty** [comment]
Actually just saw your PR, I'll double check it and the merge.
