### ISSUE TITLE
Different indicators and colors for applications not in focus.

### ISSUE THREAD

**Issue by BiudreuN** [alexankitty/FancyTasks#14]
Currently the same indicator is drawn for all applications, regardless of whether it is in focus or not. Ideally, like in Dash-to-Panel and Latte, you could define the color and layout of the indicators for unfocused apps, making them easier to identify.
Ideally, it would also be nice if the task drew its own background, being able to choose its color and radius, for focused applications.

**Comment by alexankitty** [comment]
I'll have to look at their implementations for those inactives then. Making the indicator change when the window isn't active should be easy enough, but the idea of the task deciding it's background etc seems a bit nebulous to me.

**Comment by BiudreuN** [comment]
It's just a wish. If you can't, it's not really a loss, just a small change in the chosen theme.

**Comment by alexankitty** [comment]
If latte can do it, plasma should be able to. Same language runs their indicators, just a matter of figuring out the rest of creating a library and importing it (though that might start to remove it from being a drop in replacement)
We'll have to see as I keep working on this what can be done.

**Comment by BiudreuN** [comment]
In theory it would be to delete any use of task.svg and instead put a background with the desired color. It would be like putting an indicator, but occupying all the space, and with another chosen color. Since the indicator that currently exists also allows you to round it to your liking, I don't see why the background couldn't do it.

**Comment by alexankitty** [comment]
I believe this is fixed with commit b7fc0ba2ebca4a629f4f8a6f05b1530cf3f5f9ff which includes colorize inactive buttons.

**Comment by drannex42** [comment]
Tangentially related, would it be possible to implement a "transparent" option for tasks that are inactive?

**Comment by alexankitty** [comment]
Yes this is completely and easily doable. I'll add it to the list.
