### ISSUE TITLE
Top bar is still shown

### ISSUE THREAD

**Issue by Samisafool** [alexankitty/FancyTasks#16]
![image](https://user-images.githubusercontent.com/59611020/198865239-4bd36b72-65f8-46d6-acd0-60e5fcafdbb5.png)

See, the bar on top for non-minimized apps.

**Comment by b1scu1t** [comment]
You would want to uncheck the 'Use Plasma borders' box in the Fancy Tasks configuration window.
![image](https://user-images.githubusercontent.com/41207956/198881077-911ee03a-812e-483d-b977-177a7dd6b8e2.png)

**Comment by Samisafool** [comment]
Thx
