### ISSUE TITLE
Option to use plasma accent for colorized buttons

### ISSUE THREAD

**Issue by MenacingPerson** [alexankitty/FancyTasks#20]
![image](https://user-images.githubusercontent.com/59611020/198881381-1af94fc0-ca20-41ef-abef-9ae42fa36e0d.png)

**Comment by b1scu1t** [comment]
Unchecking the 'Colorize buttons' box does exactly that...unless I'm missing something.

**Comment by heqro** [comment]
I think the problem is that the user does not get the idea that unchecking that box makes Plasma use accent color. Perhaps using Radio buttons instead may solve that confusion:

* Colorize buttons
* Use Plasma accent colors

**Comment by alexankitty** [comment]
I think this is a good idea. I'll add it to my to do list, won't be too difficult to implement.
