### ISSUE TITLE
Throws error while installing and after installation

### ISSUE THREAD

**Issue by amethylghostling** [alexankitty/FancyTasks#24]
During Installation
`cp: cannot create regular file '/home/d/.local/share/icons/hicolor/256x256/apps/FancyTasks.png': No such file or directory`

After Installation
`file:///home/d/.local/share/plasma/plasmoids/alexankitty.fancytasks/contents/ui/main.qml:414:5: Type ToolTipDelegate unavailable

file:///home/d/.local/share/plasma/plasmoids/alexankitty.fancytasks/contents/ui/ToolTipDelegate.qml:78:9: Type ToolTipInstance unavailable

file:///home/d/.local/share/plasma/plasmoids/alexankitty.fancytasks/contents/ui/ToolTipInstance.qml:155:9: PlasmaExtras.Highlight is not a type`

**Comment by mclsugi** [comment]
> cp: cannot create regular file '/home/d/.local/share/icons/hicolor/256x256/apps/FancyTasks.png': No such file or directory

That's just for the icon in widget I guess.
Workaround: Just put the .png file that is in your FT folder to the directory (create the missing folder(s) first).

**Comment by alexankitty** [comment]
This should be fixed in commit db71dcb.
