### ISSUE TITLE
FancyTasks is broken on the 5.27 beta: Cannot assign to non-existent property "dragIconSize"

### ISSUE THREAD

**Issue by namesarebloat** [alexankitty/FancyTasks#26]
the panel shows the fancytask icon only and when I click on it, it lets me copy the following text

`file:///home/$USER/.local/share/plasma/plasmoids/alexankitty.fancytasks/contents/ui/main.qml:363:9: Cannot assign to non-existent property "dragIconSize"`

Thank you for your work btw, I really like this extension.

Edit: Found the commit that causes this: https://github.com/KDE/plasma-desktop/commit/17eb382aa86107bbc39cb02c708a271f28cb07c3

**Comment by TheKarion** [comment]
Having same issue

**Comment by alexankitty** [comment]
This is functional currently, going to close.
