### ISSUE TITLE
Indicator on top doesn't work anymore

### ISSUE THREAD

**Issue by Vistaus** [alexankitty/FancyTasks#36]
Thank you for the latest update. However, showing the indicator on top of a button is now broken for me (worked fine before the update). Left and right too, btw: it only displays the indicator on the bottom regardless of the setting.

**Comment by alexankitty** [comment]
There's no useful output in there unfortunately. Maybe doing `journalctl /usr/bin/plasmashell -f` will provide something more useful. I did change the indicator to not be directly apart of the frame svg, though I need to know why your setup is ignoring the setting.

**Comment by alexankitty** [comment]
In the middle of setting up translations at the moment, I noticed you do use the Dutch translation. I have changed some of the i18ns around, so that might be why you're having problems. Let me finish getting this built into the main repo and then we go from there.

**Comment by alexankitty** [comment]
Tested under nl_NL.UTF-8 and seems to work for me. Mind updating and reporting back?

**Comment by Vistaus** [comment]
> journalctl /usr/bin/plasmashell -f

Thanks. Tried that, but there's no output related to FancyTasks in there.

**Comment by alexankitty** [comment]
Any luck with updating? May also want to remove and re-add the widget to force it to use default settings and then reconfigure. Might give me some hints on where the issue is.

**Comment by Vistaus** [comment]
Sorry for my late reply! I just re-added the widget and reconfigured everything, however, the issue is still present. :(

**Comment by alexankitty** [comment]
This makes no sense to me... Can you send me your config? Do you use it as a widget? Is it docked to the panel? Which direction is the panel?

**Comment by alexankitty** [comment]
Here's the list of variables responsible for determining the indicator location
plasmoid.configuration.indicatorOverride
plasmoid.configuration.indicatorLocation
plasmoid.location
plasmoid.configuration.indicatorReverse

```js
                    console.log(`indicatorOverride: ${plasmoid.configuration.indicatorOverride}`)
                    console.log(`indicatorLocation: ${plasmoid.configuration.indicatorLocation}`)
                    console.log(`plasmoid.location: ${plasmoid.location}`)
                    console.log(`indicatorReverse: ${plasmoid.configuration.indicatorReverse}`)
```
If you could stick the above codeblock right after line 504 in `$XDG_HOME/.local/share/plasma/plasmoids/alexankitty.fancytasks/contents/ui/Task.qml` (from AUR it's `/usr/share/plasma/plasmoids/alexankitty.fancytasks/contents/ui/Task.qml`  It would give me an idea of why the Top state won't trigger.
Once done run the following in your terminal
```sh
killall plasmashell
kstart5 plasmashell
```
That should directly log what plasma is doing to your terminal and you should be able to see the logging output look something like this.
```
qml: indicatorReverse: false
qml: indicatorOverride: false
qml: indicatorLocation: 3
qml: plasmoid.location: 4
```

**Comment by alexankitty** [comment]
[Task.zip](https://github.com/alexankitty/FancyTasks/files/12592242/Task.zip)
Or you could extract this to the directory I mentioned earlier.

**Comment by alexankitty** [comment]
Now that I think about it, you could also try rebuilding the Qt cache.
```sh
rm ~/.config/Trolltech.conf
$ kbuildsycoca5 --noincremental
```

**Comment by Vistaus** [comment]
I figured it out: it had to do with the desktop theme I was using. Changed it and now it works fine again. Thank you for all of your help! 🙂
