### ISSUE TITLE
It sometimes minimizes in the corner instead of the place where the icon on taskbar is

### ISSUE THREAD

**Issue by ziomek64** [alexankitty/FancyTasks#6]
So when I minimize it sometimes minimize to left upper corner of the screen instead of down where I have my bar with icons.  When i show all apps using left upper corner gesture it will most often go back to normal for a bit at least. Idk what's up with that. I installed it from AUR, using endeavour OS which is arch based, updated. X11

**Comment by alexankitty** [comment]
I've added this to my list to look into. I didn't test this under x11 so it'll be interesting to see what happens.

**Comment by ziomek64** [comment]
Yeah I'm on nvidia with X11. Test it for longer usage

**Comment by alexankitty** [comment]
Good to know about it being on nvidia. I worked on this on my laptop using an intel 11th gen iGPU. Might be a bit until I can test it with similar conditions as I need to use my home machine and I'm out working right now. I'll keep you posted with my findings. :)
If you think of anything else to help me recreate the issue, please let me know!

**Comment by ziomek64** [comment]
Huh, pretty weird when I restart my pc these two come up in the left upper corner
![obraz](https://user-images.githubusercontent.com/84880432/198710350-d3b75421-22de-4380-a792-b9eadb2d39ad.png)
I keep deleting and restarting but they reappear

**Comment by ziomek64** [comment]
It might be related to the bug i already mentioned

**Comment by alexankitty** [comment]
Can you send me over the config you're using as well? Screenshots of the config tool will suffice.

**Comment by ziomek64** [comment]
@alexankitty Where do I find it?

**Comment by alexankitty** [comment]
Right click a blank space in your tool bar next to the tasks and configure fancy tasks.
Though if you're just using the default config I can work from there, too.

**Comment by ziomek64** [comment]
I have it like this:
![obraz](https://user-images.githubusercontent.com/84880432/198721724-e004f37a-08a7-499c-96ee-cb35228a1f23.png)
Still weird why two appear over and over in the corner when restarting pc

**Comment by alexankitty** [comment]
Works for me. I'll try to replicate the issue and let you know what I find.

**Comment by ziomek64** [comment]
@alexankitty Those two empty blue blocks are set as flexible/elastic , idk how it is translated in english

**Comment by alexankitty** [comment]
This one is a bit confusing to me. My best guess is it might actually be an issue with the crashing issue in #7 and may have added a couple of widgets that got stuck in the corner like this. I'd see about rebuilding your panels and see if it makes the issue go away. Though I've noticed a bit of an odd issue that may be related to this problem. Depending on how the widget is docked back into the panel it can cause this weird thing to happen.

![image](https://user-images.githubusercontent.com/45508320/198817709-669c22dd-d016-4c94-8ffa-cec4e74217be.png)

More data is needed for this, but I think this might be the related issue to what you're seeing - I've fixed it on my end by resetting my panels, though I'd love to know why this dock issue happens in the first place.

**Comment by alexankitty** [comment]
Going to close this. This relates to how plasma handles minimize in general. It seems like it doesn't have great support for where to minimize the window to especially if a new task manager panel has been opened.

As for a lot of the UI weirdness with the bar itself that should be fixed since a lot of the code has been rewritten to handle things a bit more sanely.
