### ISSUE TITLE
Feature Request: Always on Top

### ISSUE THREAD

**Issue by tonytonyistony** [alexankitty/FancyTasks#64]
Not sure if this is already possible, but it would be helpful for my usage if I could not only place the widget anywhere on my screen, but keep it on top of all maximized windows.

**Comment by alexankitty** [comment]
Are widgets even capable of doing this?

**Comment by tonytonyistony** [comment]
> Are widgets even capable of doing this?
> 
> Edit: Seems to me like you either need it docked to a panel, or you have to run the widget windowed and tell the WM to make it always on top [Source](https://forum.manjaro.org/t/how-do-i-make-a-widget-be-on-top-of-everthing/57562)

Seems youre right. Im not a developer, so I wasnt sure if you had some magic up your sleeve.

**Comment by tonytonyistony** [comment]
Not possible.
