### ISSUE TITLE
Another indicator that could be made

### ISSUE THREAD

**Issue by ziomek64** [alexankitty/FancyTasks#8]
So, we have different types of indicators:
![obraz](https://user-images.githubusercontent.com/84880432/198711616-26f774e3-cdde-48dc-8544-1a1a18e92bb6.png)
Would it be possible to have dot indicator and when the window is in focus or maximized it is a dash or full sized even? I think this kind of think is on W11 and it's kinda cool

**Comment by alexankitty** [comment]
Yeah I can add it, Mind sending me a sketch of what you have in mind?

**Comment by alexankitty** [comment]
Also since it's your idea, you're welcome to give it a name as well.

**Comment by ziomek64** [comment]
Something like this:
![obraz](https://user-images.githubusercontent.com/84880432/198714059-f3db4f5c-eeb9-476b-b158-1de348d9addd.png)
As you see firefox dash is longer and the settings one is more like a dot. Sure, call it Ziomek style, just kidding. Call it Windows11 or W11

**Comment by ziomek64** [comment]
It would look cool if it had some animation of shrinking and expanding

**Comment by alexankitty** [comment]
I want to say plasma already has an animate everything approach but this should definitely be doable.
Do you know if w11 has an indicator for multiple applications open?

**Comment by ziomek64** [comment]
Yes, someone made a screenshot for me lmao, I deleted windows.
![obraz](https://user-images.githubusercontent.com/84880432/198724844-6326e32e-4480-45d8-889c-b7a172d5ea75.png)
So it's still single indicator but there's that depth underneath the whole card.

**Comment by ziomek64** [comment]
![obraz](https://user-images.githubusercontent.com/84880432/198725503-cccd5cf0-55dd-4ed3-b441-caf7d61a3804.png)
this is with multiple instances but minimized

**Comment by alexankitty** [comment]
No worries. I'm not sure if I can emulate the depth effect with the way the indicator is designed, that would have to be something seperate. It *should* be theoretically possible to make it happen by duplicating a frame underneath and shifting it to the side along with shrinking the main frame. Things to think about at least but should belong in its own issue as an enhancement.

For planning this indicator we can do the following.
The easiest method would be to use the dashes style, and add an option to enlarge (double or triple the indicator length setting) the indicator when active.
The other option we would be able to set for everything and have the indicator desaturate partially or completely (maybe a percentage like I did for border radius)
Though it could also be done as its own style, I feel it would be something that would want to be made available for all styles. 
Taking the above option we can make it work for metro and ciliora as well by having it shrink the first section of the indicator accordingly.

Let me know what you think of these ideas.

**Comment by ziomek64** [comment]
We could have dot or dash on single one  and dash and multiple dots on multiple

**Comment by ziomek64** [comment]
That would stray a little from w11 but maybe it would be nice idk

**Comment by alexankitty** [comment]
Dashes is effectively both dot and dash, it just depends on the indicator length (I originally thought about a dot style too until I realized that was really the only difference)
Ciliora could be used as a template and instead we could have a "dash ciliora"
#4 is another thing I want to add so this would allow you either increase or decrease the number of dots that are displayed for further customizability. (I followed the way it was done for lattedock's version and they decided 2 for metro and 4 for everything else)

**Comment by ziomek64** [comment]
@alexankitty did you add it? I don't seem to see anything, also that crash bug still exists. I update from AUR but no effect, i tried deleting and installing again, no effect
